# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BL_rksaoj2O0dgRplYCG_FeuJfpX9nto

### NAME : Muhammad Ali Khan

### ROLL NUMBER : AIC044380

### Teacher Name : Noman Islam

### Institute Name : Saylani Head Office Campus

### Timing : Sunday (9AM to 12PM)

# 1. Calculate Area of a Circle:

### Write a Python program which accepts the radius of a circle from the user and compute the area.

### Program Console Sample Output 1:

### Input Radius: 0.5

### Area of Circle with radius 0.5 is 0.**7855**
"""

#taking input from the user
radius=float(input("Write down the Radius:"))

#calculating area of the circle 
area_of_circle = 3.142*radius**2

#Printing area of the circle
print(f"Area with {radius} is {area_of_circle}")





"""# 2. Check Number either positive, negative or zero

### Write a Python program to check if a number is positive, negative or zero

### Program Console Sample Output 1:

### Enter Number: -1

### Negative Number Entered

### Program Console Sample Output 2:

### Integer: 3

### Positive Number Entered

### Program Console Sample Output 3:

### Integer: 0

### Zero Entered
"""

#Taking input from the user
check_num = float(input("Enter Number: "))

#Using if else conditions to check number either positive,negative or zero
if check_num > 0:
    print("Positive Number Entered")
elif check_num < 0:
    print("Negative Number Entered")
else:
    print("Zero Entered")





"""# 3. Divisibility Check of two numbers

### Write a Python program to check whether a number is completely divisible by another number. Accept two integer values form the user

### Program Console Sample Output 1:

### Enter numerator: 4
### **Enter Denominator: 2**

### Number 4 is Completely divisible by 2
### **Program Console Sample Output 2:**
### **Enter numerator: 7**
### **Enter Denominator: 4**
### Number 7 is not Completely divisible by 4 **bold text**
"""

#taking Numerator input from user
numerator = int(input("Enter Numerator: "))

#taking Denominator input from user
denominator = int(input("Enter Denominator: "))

#Using if else condiition to check the number divisibility
if numerator % denominator == 0:
    print(f"Number {numerator} is completely divisible by {denominator}")
else:
    print(f"Number {numerator} is not completely divisible by {denominator}")





"""# 4. Calculate Volume of a sphere
### **Write a Python program to get the volume of a sphere, please take the radius as input from user**
### **Program Console Output:**
### **Enter Radius of Sphere: 1**
### **Volume of the Sphere with Radius 1 is 4.189**
"""

#Taking radius as an input
radius = int(input("Enter Radius of Sphere: "))

#using formula to calculate the volume of the sphere
volume = (4/3)*3.142*radius**3

#Rounding off the volume to 3 decimal places
volume = round(volume,3)

#printing volume
print(f"Volume of the Sphere with {radius} is {volume}")





"""# **5. Copy string n times**
### **Write a Python program to get a string which is n (non-negative integer) copies of a given string.**
### **Program Console Output:**
### **Enter String: Hi**
### **How many copies of String you need: 4**
### **4 Copies of Hi are HiHiHiHi**
"""

#Taking input from the user
string_input = input("Enter String: ")
copies = int(input("How many copies of String you need: "))

#printing copies
print(f"{copies} Copies of {string_input} are {copies*string_input}")





"""# **6. Check if number is Even or Odd**
### **Write a Python program to find whether a given number (accept from the user) is even or odd, print out an appropriate message to the user**
### **Program Console Output 1:**
### **Enter Number: 4**
### **4 is Even**
### **Program Console Output 2:¶**
### **Enter Number: 9**
### **9 is Odd**
"""

#Taking input from the user
num = int(input("Enter Number: "))

#Using If else condition to check if number is even or odd
if num % 2 == 0:
    print(f"{num} is Even")
else:
    print(f"{num} is Odd")





"""# **7. Vowel Tester**
### **Write a Python program to test whether a passed letter is a vowel or not**
### **Program Console Output 1:**
### **Enter a character: A**
### **Letter A is Vowel**
### **Program Console Output 2:**
### **Enter a character: e**
### **Letter e is Vowel**
### **Program Console Output 2:**
### **Enter a character: N**
### **Letter N is not Vowel**
"""

#Taking input from the user
char = input("Enter a character: ")

#Using If else condition to check if character is vowel or not
if char.upper() in ("A","E","I","O","U"):
    print(f"Letter {char} is Vowel")
else:
    print(f"Letter {char} is not Vowel")





"""# **8. Triangle area**
### **Write a Python program that will accept the base and height of a triangle and compute the area**¶
### **Program Console Sample 1:**
### **Enter Base of a triangle: 10**
### **Enter Height of a triangle: 20**
### **The Area of triangle having base 10.0 and height 20.0 is 100.0**
"""

#Taking Input
base = float(input("Enter Base Of a triangle: "))
height = float(input("Enter Height Of a triangle: "))

#Using area formula for traingle
area = (1/2) * base * height

#Final output i.e Area of a triangle
print(f"The Area of triangle having base {base} and height {height} is {area}")





"""# **9. Calculate Interest**
### **Write a Python program to compute the future value of a specified principal amount, rate of interest, and a number of years**
### **Program Console Sample 1:**
### **Please enter principal amount: 10000**
### **Please Enter Rate of interest in %: 0.1**
### **Enter number of years for investment: 5**
### **After 5 years your principal amount 10000 over an interest rate of 0.1 % will be 16105.1**
"""

#Taking Input
amount = int(input("Please enter principal amount: "))
interest = float(input("Please Enter Rate of interest in %: "))
years = int(input("Enter number of years for investment: "))

#Using formula to compute the future value of a specified principal amount
future_value = amount * (1+interest) ** years

#Using round function to round off the result to one decimal place
future_value = round(future_value,1)

#Printing the future value
print(f"After {years} years your principal amount {amount} over an interest rate of {interest}% will be {future_value}")





"""# **10. Euclidean distance**
### **write a Python program to compute the distance between the points (x1, y1) and (x2, y2).**
### **Program Console Sample 1:**
### **Enter Co-ordinate for x1: 2**
### **Enter Co-ordinate for x2: 4**
### **Enter Co-ordinate for y1: 4**
### **Enter Co-ordinate for y2: 4**
### **Distance between points (2, 4) and (4, 4) is 2**
"""

#Taking Input
x1 = int(input("Enter Co-ordinate for x1: "))
x2 = int(input("Enter Co-ordinate for x2: "))
y1 = int(input("Enter Co-ordinate for y1:" ))
y2 = int(input("Enter Co-ordinate for y2:" ))

#Organizing Coordinates in such a pattern to use their text in final result
a1 ="("+ str(x1) + "," + str(x2) + ")"
b1="("+ str(y1) + "," + str(y2) + ")"

#Using Eclidean distance formulae
euclidean_distance = ((y1-x1)**2+(y2-x2)**2)**0.5

#Print desired results
print(f"Distance between points {a1} and {b1} is {euclidean_distance}")





"""# **11. Feet to Centimeter Converter**
### **Write a Python program to convert height in feet to centimetres.**
### **Program Console Sample 1:**
### **Enter Height in Feet: 5**
### **There are 152.4 Cm in 5 ft**
"""

#Taking Input
height_ft = float(input("Enter height in Feet: "))

#Using ft to cm formulae
height_cm = height_ft * 30.48

#Printing formulae output
print(f"There are {height_cm} Cm in {height_ft} ft")





"""# **12. BMI Calculator**
### **Write a Python program to calculate body mass index**
### **Program Console Sample 1:**
### **Enter Height in Cm: 180**
### **Enter Weight in Kg: 75**
### **Your BMI is 23.15**
"""

#Taking Input
Height = float(input("Enter Height in Cm: "))
Weight = float(input("Enter Weight in Kg: "))

#Using Formulae to caluclate BMI
BMI = Weight / ((Height * 0.01) ** 2)

#Using round() function to round off BMI To 2 decimal place
BMI = round(BMI,2)

#Printing output
print(f"Your BMI is {BMI}")





"""# **13. Sum of n Positive Integers**
### **Write a python program to sum of the first n positive integers**
### **Program Console Sample 1:**
### **Enter value of n: 5**
### **Sum of n Positive integers till 5 is 15**
"""

#taking input
value = int(input("Enter value of n: "))

#Assigning sum to zero so that loop values should be added to this sum value i.e 0
sum = 0

#using loop to print positive integers
for i in range(value+1):
#Adding the loop values in sum variable each time the loop is repeat its new value is added to the previous one
    sum = sum+i
    
#Printing Sum of n positive inteers
print(f"Sum of n Positive integers till {value} is {sum}")





"""# **14. Digits Sum of a Number**
### **Write a Python program to calculate the sum of the digits in an integer**
### **Program Console Sample 1:**
### **Enter a number: 15**
### **Sum of 1 + 5 is 6**
### **Program Console Sample 2:**
### **Enter a number: 1234**
### **Sum of 1 + 2 + 3 + 4 is 10**
"""

#Assigning sum zero value to use this variable in loop for sum of the digitis in an integer
sum = 0

#Taking input
num = input("Enter a number: ")

#Using loop to caluclate the sum of digitis in an integers 
for i in num:
    sum = sum + int(i)
    
#Printing Results
print(f"Sum of {num} is {sum}")







print("****************************************************************ALHAMD-U-LILLAH I DONE IT********************************************************************")



